apiVersion: storage.k8s.io/v1
kind: StorageClass 
metadata:
  name: managed-premium-retain-sc
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain #default is deleted recommend retain
volumeBindingMode: WaitForFirstConsumer #Default is immedaite , recommed wait for first consumer. 
allowVolumeExpansion: true
parameters:
  storageaccounttype: Premium_LRS
  kind: managed

