apiVersion: v1
kind: Service 
metadata:
  name: usermgmt-webapp-service
spec:
  type: LoadBalancer #ClusterIP NodePort
  selector:
    app: usermgmt-webapp
  ports:
    - name: tomcat
      port: 80 #service port
      targetPort: 8080 #containerPort