apiVersion: v1
kind: Service 
metadata:
  name: replicas
spec:
  type: LoadBalancer #ClusterIP NodePort
  selector:
    name: redis-replicas
  ports:
    - name: tomcat
      port: 6379 #service port
      targetPort: 6379 #containerPort